#include "token.h"

std::string_view token_type_name(TokenType type) {
    switch (type) {
    case TokenType::LeftParen:
        return "LeftParen";
    case TokenType::RightParen:
        return "RightParen";
    case TokenType::LeftBrace:
        return "LeftBrace";
    case TokenType::RightBrace:
        return "RightBrace";
    case TokenType::LeftBracket:
        return "LeftBracket";
    case TokenType::RightBracket:
        return "RightBracket";
    case TokenType::Semicolon:
        return "Semicolon";
    case TokenType::Comma:
        return "Comma";
    case TokenType::Dot:
        return "Dot";
    case TokenType::Colon:
        return "Colon";
    case TokenType::PlusOne:
        return "PlusOne";
    case TokenType::MinusOne:
        return "MinusOne";
    case TokenType::PlusEq:
        return "PlusEq";
    case TokenType::MinusEq:
        return "MinusEq";
    case TokenType::MulEq:
        return "MulEq";
    case TokenType::DivideEq:
        return "DivideEq";
    case TokenType::Plus:
        return "Plus";
    case TokenType::Minus:
        return "Minus";
    case TokenType::Star:
        return "Star";
    case TokenType::Slash:
        return "Slash";
    case TokenType::Percent:
        return "Percent";
    case TokenType::Equal:
        return "Equal";
    case TokenType::EqualEqual:
        return "EqualEqual";
    case TokenType::NotEqual:
        return "NotEqual";
    case TokenType::Not:
        return "Not";
    case TokenType::Less:
        return "Less";
    case TokenType::LessEqual:
        return "LessEqual";
    case TokenType::Greater:
        return "Greater";
    case TokenType::GreaterEqual:
        return "GreaterEqual";
    case TokenType::AndAnd:
        return "AndAnd";
    case TokenType::OrOr:
        return "OrOr";
    case TokenType::Identifier:
        return "Identifier";
    case TokenType::Number:
        return "Number";
    case TokenType::String:
        return "String";
    case TokenType::Char:
        return "Char";
    case TokenType::Var:
        return "Var";
    case TokenType::Print:
        return "Print";
    case TokenType::EndOfFile:
        return "EndOfFile";
    case TokenType::True:
        return "True";
    case TokenType::False:
        return "False";
    case TokenType::Null:
        return "Null";
    case TokenType::If:
        return "If";
    case TokenType::Else:
        return "Else";
    case TokenType::While:
        return "While";
    case TokenType::For:
        return "For";
    case TokenType::In:
        return "In";
    case TokenType::Break:
        return "Break";
    case TokenType::Continue:
        return "Continue";
    case TokenType::Fun:
        return "Fun";
    case TokenType::Return:
        return "Return";
    case TokenType::Array:
        return "Array";
    case TokenType::Class:
        return "Class";
    case TokenType::Count:
        return "Count";
    case TokenType::Map:
        return "Map";
    }

    return "Unknown";
}
